version: '3.9'

services:
  server:
    ports:
      - 5335:3300
    container_name: sushitakeout
    networks:
      - nginx-proxy-manager_default
    restart: always
    build: .

networks:
  nginx-proxy-manager_default:
    external: true
